# Build ai_gen_src/.env.greennode from local .env (runtime container env — no GREENNODE_* auto-inject vars).
param(
    [string]$SourceEnv = "",
    [string]$OutFile = ""
)

$AiGenSrc = Split-Path $PSScriptRoot -Parent
if (-not $SourceEnv) { $SourceEnv = Join-Path $AiGenSrc ".env" }
if (-not $OutFile) { $OutFile = Join-Path $AiGenSrc ".env.greennode" }

$skip = @("GREENNODE_CLIENT_ID", "GREENNODE_CLIENT_SECRET", "GREENNODE_AGENT_IDENTITY", "GREENNODE_ENDPOINT_URL")
$defaults = @{
    API_ADDR = ":8080"
    CORS_ORIGIN = "*"
    DATA_SOURCE = "mock"
    DEV_AUTH_BYPASS = "true"
    AGENT_LOCALE = "vi-VN"
    APP_TIMEZONE = "Asia/Ho_Chi_Minh"
    NOTIFICATION_MOCK = "true"
}

$lines = @(
    "# OpsOne API on GreenNode AgentBase — generated by prepare-greennode-env.ps1",
    "# Edit MYSQL_DSN to a MySQL host reachable from public AgentBase runtime.",
    ""
)

if (Test-Path $SourceEnv) {
    Get-Content $SourceEnv | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#")) { return }
        $eq = $line.IndexOf("=")
        if ($eq -lt 1) { return }
        $key = $line.Substring(0, $eq).Trim()
        if ($skip -contains $key) { return }
        $lines += $_
    }
} else {
    Write-Warning "Source $SourceEnv not found — writing template defaults only."
}

foreach ($kv in $defaults.GetEnumerator()) {
    $has = $lines | Where-Object { $_ -match "^\s*$([regex]::Escape($kv.Key))\s*=" }
    if (-not $has) { $lines += "$($kv.Key)=$($kv.Value)" }
}

if (-not ($lines | Where-Object { $_ -match '^\s*MYSQL_DSN\s*=' })) {
    $lines += 'MYSQL_DSN=app:secret@tcp(YOUR_MYSQL_HOST:3306)/opsone?parseTime=true&charset=utf8mb4&loc=Asia%2FHo_Chi_Minh'
}

Set-Content -Path $OutFile -Value ($lines -join "`n") -Encoding UTF8
Write-Host "Wrote $OutFile"
Write-Host "Next: set MYSQL_DSN to cloud MySQL, then run .\scripts\deploy-greennode.ps1"
